/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -i QtTelepathy/Core/ChannelInterfaceDTMFAdaptor -a :src/Core/channelinterfacedtmfadaptor.cpp xml/Channel_Interface_DTMF.xml
 *
 * dbusxml2cpp is Copyright (C) 2006 Trolltech ASA. All rights reserved.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "channelinterfacedtmfadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DTMFAdaptor
 */

DTMFAdaptor::DTMFAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DTMFAdaptor::~DTMFAdaptor()
{
    // destructor
}

void DTMFAdaptor::StartTone(uint stream_id, uchar event)
{
    // handle method call org.freedesktop.Telepathy.Channel.Interface.DTMF.StartTone
    QMetaObject::invokeMethod(parent(), "StartTone", Q_ARG(uint, stream_id), Q_ARG(uchar, event));
}

void DTMFAdaptor::StopTone(uint stream_id)
{
    // handle method call org.freedesktop.Telepathy.Channel.Interface.DTMF.StopTone
    QMetaObject::invokeMethod(parent(), "StopTone", Q_ARG(uint, stream_id));
}

