/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -i QtTelepathy/Core/ChannelAdaptor -a :src/Core/channeladaptor.cpp xml/tp-chan.xml
 *
 * dbusxml2cpp is Copyright (C) 2006 Trolltech ASA. All rights reserved.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

// THIS FILE WAS MANUALLY EDITED! DO NOT REGENERATE!

#include "channeladaptor.h"
#include "channel.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ChannelAdaptor
 */

ChannelAdaptor::ChannelAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ChannelAdaptor::~ChannelAdaptor()
{
    // destructor
}

void ChannelAdaptor::Close()
{
    // handle method call org.freedesktop.Telepathy.Channel.Close
    QMetaObject::invokeMethod(parent(), "Close");
}

QString ChannelAdaptor::GetChannelType()
{
    // handle method call org.freedesktop.Telepathy.Channel.GetChannelType
    QString out0;
    QMetaObject::invokeMethod(parent(), "GetChannelType", Q_RETURN_ARG(QString, out0));
    return out0;
}

uint ChannelAdaptor::GetHandle(uint &id)
{
    // handle method call org.freedesktop.Telepathy.Channel.GetHandle
    return static_cast<Channel *>(parent())->GetHandle(id);
}

QStringList ChannelAdaptor::GetInterfaces()
{
    // handle method call org.freedesktop.Telepathy.Channel.GetInterfaces
    QStringList out0;
    QMetaObject::invokeMethod(parent(), "GetInterfaces", Q_RETURN_ARG(QStringList, out0));
    return out0;
}

