/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -i QtTelepathy/Common/BaseTypes -a include/QtTelepathy/Core/channeladaptor.h: xml/tp-chan.xml
 *
 * dbusxml2cpp is Copyright (C) 2006 Trolltech ASA. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef CHANNELADAPTOR_H_1172489891
#define CHANNELADAPTOR_H_1172489891

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "basetypes.h"
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.freedesktop.Telepathy.Channel
 */
class ChannelAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.Telepathy.Channel")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.Telepathy.Channel\" >\n"
"    <method name=\"Close\" />\n"
"    <method name=\"GetChannelType\" >\n"
"      <arg direction=\"out\" type=\"s\" />\n"
"    </method>\n"
"    <method name=\"GetHandle\" >\n"
"      <arg direction=\"out\" type=\"u\" name=\"type\" />\n"
"      <arg direction=\"out\" type=\"u\" name=\"id\" />\n"
"    </method>\n"
"    <method name=\"GetInterfaces\" >\n"
"      <arg direction=\"out\" type=\"as\" />\n"
"    </method>\n"
"    <signal name=\"Closed\" />\n"
"  </interface>\n"
        "")
public:
    ChannelAdaptor(QObject *parent);
    virtual ~ChannelAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void Close();
    QString GetChannelType();
    uint GetHandle(uint &id);
    QStringList GetInterfaces();
Q_SIGNALS: // SIGNALS
    void Closed();
};

#endif
