/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -i QtTelepathy/Common/BaseTypes -a include/QtTelepathy/Core/connectioninterfaceprivacyadaptor.h: xml/tp-conn-iface-privacy.xml
 *
 * dbusxml2cpp is Copyright (C) 2006 Trolltech ASA. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef CONNECTIONINTERFACEPRIVACYADAPTOR_H_1172489892
#define CONNECTIONINTERFACEPRIVACYADAPTOR_H_1172489892

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "basetypes.h"
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.freedesktop.Telepathy.Connection.Interface.Privacy
 */
class PrivacyAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.Telepathy.Connection.Interface.Privacy")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.Telepathy.Connection.Interface.Privacy\" >\n"
"    <method name=\"GetPrivacyMode\" >\n"
"      <arg direction=\"out\" type=\"s\" />\n"
"    </method>\n"
"    <method name=\"GetPrivacyModes\" >\n"
"      <arg direction=\"out\" type=\"as\" />\n"
"    </method>\n"
"    <method name=\"SetPrivacyMode\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"mode\" />\n"
"    </method>\n"
"    <signal name=\"PrivacyModeChanged\" >\n"
"      <arg type=\"s\" name=\"mode\" />\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    PrivacyAdaptor(QObject *parent);
    virtual ~PrivacyAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QString GetPrivacyMode();
    QStringList GetPrivacyModes();
    void SetPrivacyMode(const QString &mode);
Q_SIGNALS: // SIGNALS
    void PrivacyModeChanged(const QString &mode);
};

#endif
