/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c VicarCallRouterProxy -p vicarcallrouterproxy.h:vicarcallrouterproxy.cpp org.maemo.vicar.xml org.maemo.vicar
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef VICARCALLROUTERPROXY_H_1280455099
#define VICARCALLROUTERPROXY_H_1280455099

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.maemo.vicar
 */
class VicarCallRouterProxy: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.maemo.vicar"; }

public:
    VicarCallRouterProxy(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~VicarCallRouterProxy();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QString> callInternationalNumber(const QString &number)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(number);
        return asyncCallWithArgumentList(QLatin1String("callInternationalNumber"), argumentList);
    }

    inline QDBusPendingReply<bool> isRunning()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("isRunning"), argumentList);
    }

    inline QDBusPendingReply<bool> startOutgoingCallMonitor()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("startOutgoingCallMonitor"), argumentList);
    }

    inline QDBusPendingReply<bool> stopOutgoingCallMonitor()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("stopOutgoingCallMonitor"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace org {
  namespace maemo {
    typedef ::VicarCallRouterProxy vicar;
  }
}
#endif
